export const actionTypes = {
    FETCH_ALL: 'FETCH_ALL',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    LIKE: 'LIKE',
    AUTH: 'AUTH',
    LOGOUT: 'LOGOUT',
    BAD_AUTH: 'BAD_AUTH',
    PASS_MISMATCH: 'PASS_MISMATCH',
    USER_EXISTS: 'USER_EXISTS'
}
